import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function AnalysisPreviewScreen() {
  const [matchId, setMatchId] = useState<string | null>(null);
  const create = trpc.mahjong.create.useMutation({ onSuccess: (match) => setMatchId(match.id) });
  const legality = trpc.mahjong.legalityPreview.useQuery({ id: matchId ?? "", seat: 0 }, { enabled: Boolean(matchId) });
  const score = trpc.mahjong.scorePreview.useQuery({ id: matchId ?? "", seat: 0, tsumo: false, riichi: false, doraCount: 0 }, { enabled: Boolean(matchId) });
  const contributions = trpc.mahjong.aiContributions.useQuery({ id: matchId ?? "", seat: 0, policy: "balanced" }, { enabled: Boolean(matchId) });
  return <ScreenContainer className="px-5 pt-5"><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><View className="gap-5"><Pressable onPress={() => router.back()}><Text className="font-semibold text-primary">‹ Back</Text></Pressable><View><Text className="text-sm font-semibold uppercase tracking-widest text-primary">Decision preview</Text><Text className="mt-1 text-4xl font-bold text-foreground">Understand before acting.</Text><Text className="mt-2 text-base leading-6 text-muted">The backend explains which actions are legal, what a starter score estimate contains, and which AI signals shaped the recommendation.</Text></View><Pressable onPress={() => create.mutate({ seed: Date.now() })} className="rounded-2xl bg-primary p-4"><Text className="text-center font-bold text-background">{create.isPending ? "Creating state…" : "Create preview state"}</Text></Pressable>{matchId ? <><View className="rounded-2xl border border-border bg-surface p-4"><Text className="text-xl font-bold text-foreground">Legal actions</Text>{legality.isLoading ? <ActivityIndicator /> : <View className="mt-3 gap-2">{Object.entries(legality.data ?? {}).map(([key, value]) => <View key={key} className="flex-row items-center justify-between"><Text className="capitalize text-foreground">{key}</Text><Text className={typeof value === "object" ? "text-muted" : value ? "font-bold text-success" : "text-muted"}>{typeof value === "object" ? (value as { allowed: boolean; reason?: string }).allowed ? "Allowed" : (value as { reason?: string }).reason ?? "Not available" : value ? "Available" : "Not available"}</Text></View>)}</View>}</View><View className="rounded-2xl border border-border bg-surface p-4"><Text className="text-xl font-bold text-foreground">Score preview</Text>{score.data ? <><Text className="mt-2 text-3xl font-bold text-foreground">{score.data.points.toLocaleString()} points</Text><Text className="mt-1 text-sm text-muted">{score.data.han} han · {score.data.fu} fu · {score.data.yaku.join(", ") || "No detected starter yaku"}</Text></> : <Text className="mt-2 text-muted">A complete hand is required for a production score. This preview remains conservative.</Text>}</View><View className="rounded-2xl border border-border bg-surface p-4"><Text className="text-xl font-bold text-foreground">AI contribution breakdown</Text>{(contributions.data ?? []).map((item) => <View key={item.feature} className="mt-3"><View className="flex-row justify-between"><Text className="capitalize text-foreground">{item.feature}</Text><Text className="font-semibold text-primary">{item.contribution.toFixed(2)}</Text></View><Text className="mt-1 text-xs leading-4 text-muted">{item.explanation}</Text></View>)}</View></> : <Text className="py-8 text-center leading-6 text-muted">Create a preview state to inspect legality, scoring, and AI reasoning.</Text>}</View></ScrollView></ScreenContainer>;
}
