import { Text, View } from "react-native";
import { ArenaButton, ArenaCard } from "@/components/arena-ui";
import type { AIMatchReport, ReplayAnalytics } from "@/shared/mahjong-backend";

export function MatchAnalyticsPanel({ analytics, report, chatReady, onReview, onHistory }: { analytics?: ReplayAnalytics; report?: AIMatchReport; chatReady?: boolean; onReview: () => void; onHistory: () => void }) {
  if (!analytics && !report) return <ArenaCard eyebrow="Match analytics" title="No replay data yet"><Text style={{ color: "#C0BBA8", fontSize: 13, lineHeight: 19, marginTop: 8 }}>Complete a few AI decisions to unlock confidence, score, and Sensei context.</Text></ArenaCard>;
  const confidence = analytics?.averageConfidence ?? 0;
  const decisionCount = analytics?.decisionCount ?? report?.decisions ?? 0;
  const scores = analytics?.scoreContext.scores ?? report?.scores ?? {};
  const objectiveCount = Object.keys(analytics?.byObjective ?? {}).length;
  return <ArenaCard eyebrow="Match analytics" title={`${decisionCount} decisions analyzed`}><View style={{ flexDirection: "row", gap: 8, marginTop: 14 }}><View style={{ flex: 1, borderRadius: 12, padding: 12, backgroundColor: "rgba(26,58,47,0.72)" }}><Text style={{ color: "#A7B9AC", fontSize: 10, textTransform: "uppercase" }}>Confidence</Text><Text style={{ color: "#F5F0E8", fontSize: 20, fontWeight: "800", marginTop: 4 }}>{Math.round(confidence * 100)}%</Text></View><View style={{ flex: 1, borderRadius: 12, padding: 12, backgroundColor: "rgba(26,58,47,0.72)" }}><Text style={{ color: "#A7B9AC", fontSize: 10, textTransform: "uppercase" }}>Objectives</Text><Text style={{ color: "#F5F0E8", fontSize: 20, fontWeight: "800", marginTop: 4 }}>{objectiveCount || "—"}</Text></View></View><Text style={{ color: "#C0BBA8", fontSize: 12, lineHeight: 18, marginTop: 12 }}>{analytics ? `${analytics.scoreContext.roundWind} · hand ${analytics.scoreContext.handNumber} · dealer seat ${analytics.scoreContext.dealer}` : report?.phase}</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 10 }}>{Object.entries(scores).slice(0, 4).map(([seat, score]) => <View key={seat} style={{ borderRadius: 10, paddingHorizontal: 9, paddingVertical: 7, backgroundColor: "rgba(255,255,255,0.06)" }}><Text style={{ color: "#A7B9AC", fontSize: 10 }}>Seat {seat}</Text><Text style={{ color: "#F5F0E8", fontSize: 12, fontWeight: "800" }}>{score.toLocaleString()}</Text></View>)}</View><Text style={{ color: chatReady ? "#A7B9AC" : "#D7AA58", fontSize: 11, marginTop: 12 }}>{chatReady ? "Sensei context is ready for this replay." : "Sensei context will be available when a match is active."}</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 14 }}><ArenaButton label="Review" variant="jade" onPress={onReview} style={{ flex: 1 }} /><ArenaButton label="History" variant="ghost" onPress={onHistory} style={{ flex: 1 }} /></View></ArenaCard>;
}
